# -*- coding: utf-8 -*-
"""EDA_The Daily Bugle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18cX42Zf79JhSMfDVPN8qBq_UDERY4Vut

# Final EDA Analysis

This notebook contains the descriptive and diagnostic analysis for the manga/anime adaptation project.

The goal of this EDA is to understand the structure of the finalized manga modeling dataset before regression modeling.

This notebook covers:

1. Final dataset overview  
2. Animated vs. unanimated group count  
3. Sample A/B/C overview  
4. Audience engagement and quality benchmarks  
5. Publication status distribution  
6. Demographic distribution  
7. Genre distribution  
8. Diagnostic notes and limitations
"""

# ============================================================
# 1. Import Libraries
# ============================================================

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# os.chdir(r"C:\Users\신현\Desktop\BA")
print("Current folder:")
print(os.getcwd())
pd.set_option("display.max_columns", 80)
pd.set_option("display.width", 1200)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

"""## Load Finalized Dataset and Modeling Samples

We load the finalized manga modeling dataset and the three modeling samples.

- Finalized dataset: full manga modeling dataset with `has_anime`
- Sample A: score-based sample
- Sample B: favorites-based sample
- Sample C: members-based sample

For EDA, Sample C is additionally filtered with `members >= 1000` to match the final active-market definition.
"""

# ============================================================
# 2. Load Finalized Dataset and Modeling Samples
# ============================================================

csv_files = [f for f in os.listdir() if f.endswith(".csv")]

print("CSV files in this folder:")
print(csv_files)

final_file = [f for f in csv_files if "finalized_manga_modeling_dataset" in f.lower()][0]
sample_a_file = [f for f in csv_files if "sample_a_score_modeling" in f.lower()][0]
sample_b_file = [f for f in csv_files if "sample_b_favorites_modeling" in f.lower()][0]
sample_c_file = [f for f in csv_files if "sample_c_members_modeling" in f.lower()][0]

final_df = pd.read_csv(final_file)
sample_a = pd.read_csv(sample_a_file)
sample_b = pd.read_csv(sample_b_file)
sample_c = pd.read_csv(sample_c_file)

# Final active-market version of Sample C
sample_c_active = sample_c[sample_c["members"] >= 1000].copy()

print("\nLoaded datasets:")
print("Finalized dataset:", final_file, final_df.shape)
print("Sample A:", sample_a_file, sample_a.shape)
print("Sample B:", sample_b_file, sample_b.shape)
print("Sample C original:", sample_c_file, sample_c.shape)
print("Sample C active-market, members >= 1000:", sample_c_active.shape)

"""## Final Dataset Overview

The unit of analysis is an individual manga title.

The dependent variable is `has_anime`.

- `has_anime = 1`: the manga title was matched with the anime dataset.
- `has_anime = 0`: the manga title was not matched with the anime dataset.

This allows us to separate already adapted manga from the unanimated candidate pool.
"""

# ============================================================
# 3. Final Dataset Overview
# ============================================================

overview = pd.DataFrame({
    "Metric": [
        "Total manga titles",
        "Animated / Already Adapted",
        "Unanimated / Candidate Pool"
    ],
    "Count": [
        len(final_df),
        int(final_df["has_anime"].sum()),
        int((final_df["has_anime"] == 0).sum())
    ]
})

overview["Percentage"] = (overview["Count"] / len(final_df) * 100).round(2)

display(overview)

overview.to_csv("eda_final_dataset_overview.csv", index=False)
overview.to_html("eda_final_dataset_overview.html", index=False)

print("Saved files:")
print("eda_final_dataset_overview.csv")
print("eda_final_dataset_overview.html")

"""## Final Dataset Animated vs. Unanimated Manga Distribution

The distribution visualization shows title matching successfully identified 5,378 (6.5%) animated manga and 77,511 (93%) that were not animated.
"""

# ============================================================
# Distribution Analysis: Target Variable (Has Anime)
# ============================================================
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os

# 1. Load the finalized modeling dataset
csv_file = "finalized_manga_modeling_dataset.csv"

if os.path.exists(csv_file):
    df = pd.read_csv(csv_file)
    print(f"✅ Successfully loaded finalized dataset: '{csv_file}'")
    print(f"📋 Total titles in dataset: {len(df):,}")
else:
    raise FileNotFoundError(f"❌ Error: Could not find '{csv_file}' in your current folder. Please check the spelling or path!")

# 2. Verify target column exists (handling potential capitalization variants)
target_col = None
for col in ['has_anime', 'Has_Anime', 'HasAnime', 'hasAnime']:
    if col in df.columns:
        target_col = col
        break

if not target_col:
    print("Available columns:", df.columns.tolist())
    raise KeyError("❌ Could not find a 'has_anime' column in your CSV. Check the printed list above!")

# 3. Set sophisticated presentation style
sns.set_theme(style="whitegrid")
plt.figure(figsize=(7, 5), dpi=300)

# Corporate color scheme (Muted Gray for No Anime, Distinct Blue for Has Anime)
corporate_colors = ["#b0bec5", "#2171b5"]

# 4. Generate the count plot
ax = sns.countplot(
    x=target_col,
    data=df,
    palette=corporate_colors,
    edgecolor="black",
    linewidth=0.8,
    width=0.5
)

# 5. Dynamic percentage and count text overlays on top of the bars
total_titles = len(df)
for p in ax.patches:
    height = p.get_height()
    percentage = (height / total_titles) * 100
    ax.annotate(
        f'{height:,}\n({percentage:.1f}%)',
        xy=(p.get_x() + p.get_width() / 2., height),
        xytext=(0, 8),  # 8 points vertical offset
        textcoords="offset points",
        ha='center',
        va='bottom',
        weight='bold',
        fontsize=11
    )

# 6. Polished Slide Presentation Formatting
plt.title('Animated vs. Non-Animated Manga Titles', fontsize=13, fontweight='bold', pad=15)
plt.xlabel('Anime Adaptation Status', fontsize=11, labelpad=10)
plt.ylabel('Number of Manga Titles', fontsize=11, labelpad=10)

# Clean up x-axis labels from 0/1 to clear business terminology
ax.set_xticklabels(['No Anime Flag (0)', 'Has Anime Flag (1)'], fontsize=11, weight='bold')

# Expand y-axis upper limit slightly so text overlays don't clip against the top border
ax.set_ylim(0, df[target_col].value_counts().max() * 1.15)

# Remove distracting top and right spine borders
sns.despine(left=True, bottom=False)

# 7. Save out clean high-res image
output_image = "target_variable_distribution.png"
plt.savefig(output_image, bbox_inches='tight')
print(f"🎨 Success! Distribution chart saved to your folder as '{output_image}'")
plt.show()

"""## Visualization - Final Dataset Missing Values: Scores

The finalized dataset distribution shows the score variable has 52,220 (63%) missing values.
"""

# ============================================================
# Data Limitation Chart: Missing Score Breakdown
# ============================================================
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# 1. Input your exact verified audit metrics
total_titles = 82889
missing_scores = 52220
present_scores = total_titles - missing_scores

# Calculate precise presentation percentages
pct_missing = (missing_scores / total_titles) * 100
pct_present = (present_scores / total_titles) * 100

# 2. Create a clean dataframe structured for modern corporate styling
data = {
    'Status': ['Missing Score Value', 'Valid Score Present'],
    'Count': [missing_scores, present_scores],
    'Percentage': [pct_missing, pct_present]
}
df_limitation = pd.DataFrame(data)

# 3. Initialize minimalist theme
sns.set_theme(style="whitegrid")
fig, ax = plt.subplots(figsize=(8, 3.5), dpi=300)

# Corporate color scheme: Sharp alert coral/red for missing data, muted slate for valid data
presentation_colors = ["#e6550d", "#969696"]

# 4. Draw horizontal bar chart
bars = ax.barh(
    df_limitation['Status'],
    df_limitation['Count'],
    color=presentation_colors,
    edgecolor="black",
    height=0.55,
    alpha=0.9
)

# 5. Overlay clean, high-visibility metric text labels
for bar, pct, count in zip(bars, df_limitation['Percentage'], df_limitation['Count']):
    width = bar.get_width()
    ax.annotate(
        f' {count:,} titles ({pct:.1f}%)',
        xy=(width, bar.get_y() + bar.get_height() / 2),
        xytext=(5, 0),  # Padding slightly to the right of the bar boundary
        textcoords="offset points",
        ha='left',
        va='center',
        weight='bold',
        fontsize=11
    )

# 6. Polished Slate Layout Details (Zero clutter)
ax.set_title("Score Availability", fontsize=12, fontweight="bold", pad=15, loc="left")
ax.set_xlabel("Total Manga Count", fontsize=10, labelpad=8)
ax.set_ylabel("")

# Safely expand the x-axis limits so trailing text labels don't get chopped off
ax.set_xlim(0, total_titles * 1.35)

# Emphasize category labels for presentation slides
ax.set_yticklabels(df_limitation['Status'], fontsize=11, weight='bold')

# Drop distracting grid boxes
sns.despine(left=True, bottom=False)
plt.tight_layout()

# Save image out directly
output_name = "data_limitation_missing_scores.png"
plt.savefig(output_name, bbox_inches='tight')
print(f"🎨 Clean data limitation graphic saved as '{output_name}'")
plt.show()

"""## Sample-Level Overview

We created three samples based on the main variables suggested for modeling: score, favorites, and members.

- Sample A tests score using titles with available score data.
- Sample B uses the broader manga dataset to examine favorites-based fan engagement.
- Sample C uses an active-market filter, `members >= 1000`, to focus on titles with baseline audience visibility.
"""

# ============================================================
# 4. Sample-Level Overview
# ============================================================

def sample_overview(df, sample_name):
    total_rows = len(df)
    animated_count = int(df["has_anime"].sum())
    unanimated_count = int((df["has_anime"] == 0).sum())

    return {
        "Sample": sample_name,
        "Total rows": total_rows,
        "Animated count": animated_count,
        "Unanimated count": unanimated_count,
        "Animated percentage": round(animated_count / total_rows * 100, 2)
    }

sample_summary = pd.DataFrame([
    sample_overview(sample_a, "Sample A — Score Model"),
    sample_overview(sample_b, "Sample B — Favorites Model"),
    sample_overview(sample_c_active, "Sample C — Members / Active-Market Model")
])

display(sample_summary)

sample_summary.to_csv("eda_sample_overview.csv", index=False)
sample_summary.to_html("eda_sample_overview.html", index=False)

print("Saved files:")
print("eda_sample_overview.csv")
print("eda_sample_overview.html")

"""## Audience Engagement and Quality Benchmarks

This section summarizes the average and median values of score, members, and favorites among already animated manga.

These are descriptive benchmarks only. They show historical patterns, not statistical relationships.
"""

# ============================================================
# 5. Audience Engagement and Quality Benchmarks
# ============================================================

def animated_benchmarks(df, sample_name):
    animated = df[df["has_anime"] == 1].copy()

    return {
        "Sample": sample_name,
        "Animated count": len(animated),
        "Average score": round(animated["score"].mean(), 2) if "score" in animated.columns else np.nan,
        "Average members": round(animated["members"].mean(), 0),
        "Median members": round(animated["members"].median(), 0),
        "Average favorites": round(animated["favorites"].mean(), 0),
        "Median favorites": round(animated["favorites"].median(), 0)
    }

benchmarks = pd.DataFrame([
    animated_benchmarks(sample_a, "Sample A — Score Model"),
    animated_benchmarks(sample_b, "Sample B — Favorites Model"),
    animated_benchmarks(sample_c_active, "Sample C — Members / Active-Market Model")
])

display(benchmarks)

benchmarks.to_csv("eda_audience_quality_benchmarks.csv", index=False)
benchmarks.to_html("eda_audience_quality_benchmarks.html", index=False)

print("Saved files:")
print("eda_audience_quality_benchmarks.csv")
print("eda_audience_quality_benchmarks.html")

"""Sample A:
Animated manga with score data have average score 7.31.
Average members = 18,357, but median members = 3,912.
Average favorites = 856, but median favorites = 38.

Sample B:
Because this sample represents our broader dataset baseline without removing lower-visibility titles,
the average and median numbers for both members and favorites are lower compared to the other groups.

Sample C:
We applied a specific filter of members >= 1000 to ensure we keep only active-market titles in the analysis.
Since we removed titles with very low consumer interest, this sample features the highest average numbers
for both members and favorites.

## Visualization - Benchmarks
"""

# Isolate the average score metric from our benchmarks dataframe
plot_score = benchmarks[['Sample', 'Average score']].copy()

# Set up the visualization style and plot layout
sns.set_theme(style="whitegrid")
fig, ax = plt.subplots(figsize=(10, 5), dpi=100)

# Generate a clean bar chart for the scores
bars_score = ax.bar(plot_score['Sample'], plot_score['Average score'], width=0.4,
                     color='mediumpurple', alpha=0.9)

# Add clear labels, title, and structure adjustments
ax.set_title('Comparison of Average Quality Scores Across Samples', fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Data Modeling Samples', fontsize=12, labelpad=10)
ax.set_ylabel('Average User Score (1-10 Scale)', fontsize=12)
ax.set_ylim(0, 10)  # Set limit to show full standard score scale
ax.set_xticklabels(plot_score['Sample'], fontsize=10)

# Annotate values clearly on top of each bar for easy reading
for bar in bars_score:
    height = bar.get_height()
    if not pd.isna(height):
        ax.annotate(f'{height:.2f}',
                    xy=(bar.get_x() + bar.get_width() / 2, height),
                    xytext=(0, 3),  # Offset label slightly above the bar
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.savefig('sample_score_benchmarks_chart.png')
plt.show()

print("Visualization successfully built and saved as 'sample_score_benchmarks_chart.png'!")

# Prepare the dataset for graphing by isolating members metrics from our benchmarks
plot_data = benchmarks[['Sample', 'Average members', 'Median members']].copy()

# Set up the visualization style and plot layout
sns.set_theme(style="whitegrid")
fig, ax = plt.subplots(figsize=(11, 6), dpi=100)

# Define exact locations for grouped bars
x_indices = np.arange(len(plot_data['Sample']))
bar_width = 0.35

# Generate grouped bars for Average vs Median metrics
bars_avg = ax.bar(x_indices - bar_width/2, plot_data['Average members'], width=bar_width,
                  label='Average Members (Reach)', color='royalblue', alpha=0.9)
bars_med = ax.bar(x_indices + bar_width/2, plot_data['Median members'], width=bar_width,
                  label='Median Members (Threshold)', color='teal', alpha=0.9)

# Add clear labels, title, and structure adjustments
ax.set_title('Comparison of Audience Reach and Midpoint Thresholds Across Samples', fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Data Modeling Samples', fontsize=12, labelpad=10)
ax.set_ylabel('Total Member Count (Users)', fontsize=12)
ax.set_xticks(x_indices)
ax.set_xticklabels(plot_data['Sample'], fontsize=10)
ax.legend(fontsize=11)

# Annotate values clearly on top of each individual bar for quick reading
def apply_bar_labels(bars):
    for bar in bars:
        height = bar.get_height()
        if not pd.isna(height):
            ax.annotate(f'{int(height):,}',
                        xy=(bar.get_x() + bar.get_width() / 2, height),
                        xytext=(0, 3),  # Offset label slightly above the bar
                        textcoords="offset points",
                        ha='center', va='bottom', fontsize=9, fontweight='bold')

apply_bar_labels(bars_avg)
apply_bar_labels(bars_med)

plt.tight_layout()
plt.savefig('sample_reach_benchmarks_chart.png')
plt.show()

print("Visualization successfully built and saved as 'sample_reach_benchmarks_chart.png'!")

# Isolate the favorites metrics from our benchmarks dataframe
plot_favorites = benchmarks[['Sample', 'Average favorites', 'Median favorites']].copy()

# Set up the visualization style and plot layout
sns.set_theme(style="whitegrid")
fig, ax = plt.subplots(figsize=(11, 6), dpi=100)

# Define exact locations for grouped bars
x_indices = np.arange(len(plot_favorites['Sample']))
bar_width = 0.35

# Generate grouped bars for Average vs Median Favorites
bars_fav_avg = ax.bar(x_indices - bar_width/2, plot_favorites['Average favorites'], width=bar_width,
                      label='Average Favorites (Fan Base Size)', color='coral', alpha=0.9)
bars_fav_med = ax.bar(x_indices + bar_width/2, plot_favorites['Median favorites'], width=bar_width,
                      label='Median Favorites (Baseline Level)', color='crimson', alpha=0.9)

# Add labels, title, and formatting adjustments
ax.set_title('Comparison of Fan Favorites Across Modeling Samples', fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Data Modeling Samples', fontsize=12, labelpad=10)
ax.set_ylabel('Total Favorites Count (Users)', fontsize=12)
ax.set_xticks(x_indices)
ax.set_xticklabels(plot_favorites['Sample'], fontsize=10)
ax.legend(fontsize=11)

# Annotate values on top of each bar for easy reading
def apply_bar_labels(bars):
    for bar in bars:
        height = bar.get_height()
        if not pd.isna(height):
            ax.annotate(f'{int(height):,}',
                        xy=(bar.get_x() + bar.get_width() / 2, height),
                        xytext=(0, 3),  # Offset label slightly above the bar
                        textcoords="offset points",
                        ha='center', va='bottom', fontsize=9, fontweight='bold')

apply_bar_labels(bars_fav_avg)
apply_bar_labels(bars_fav_med)

plt.tight_layout()
plt.savefig('sample_favorites_benchmarks_chart.png')
plt.show()

print("Visualization built successfully and saved as 'sample_favorites_benchmarks_chart.png'!")

"""## Publication Status Distribution

This section shows the current publication status of already animated manga.

Important limitation: publication status reflects the current dataset snapshot. It does not necessarily show the status at the time of licensing or first anime adaptation.
"""

# ============================================================
# 6. Publication Status Distribution
# ============================================================

status_cols = [col for col in final_df.columns if col.startswith("status_")]

def status_distribution(df, sample_name):
    animated = df[df["has_anime"] == 1].copy()
    total = len(animated)

    rows = []
    for col in status_cols:
        if col in animated.columns:
            count = int(animated[col].sum())
            rows.append({
                "Sample": sample_name,
                "Status": col.replace("status_", ""),
                "Count": count,
                "Percentage": round(count / total * 100, 2)
            })
    return rows

status_summary = pd.DataFrame(
    status_distribution(sample_a, "Sample A — Score Model")
    + status_distribution(sample_b, "Sample B — Favorites Model")
    + status_distribution(sample_c_active, "Sample C — Members / Active-Market Model")
)

display(status_summary)

status_summary.to_csv("eda_status_distribution.csv", index=False)
status_summary.to_html("eda_status_distribution.html", index=False)

print("Saved files:")
print("eda_status_distribution.csv")
print("eda_status_distribution.html")

"""## Visualization - Publication Status Distribution"""

# Set up the visualization style and plot layout
sns.set_theme(style="whitegrid")
fig, ax = plt.subplots(figsize=(12, 6), dpi=100)

# Create a grouped bar chart using seaborn, plotting percentages for comparison
sns.barplot(
    data=status_summary,
    x="Sample",
    y="Percentage",
    hue="Status",
    palette="muted",
    alpha=0.9,
    ax=ax
)

# Add clear labels, title, and formatting adjustments
ax.set_title('Publication Status Distribution of Animated Manga Across Samples', fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Data Modeling Samples', fontsize=12, labelpad=10)
ax.set_ylabel('Percentage of Animated Titles (%)', fontsize=12)
ax.set_ylim(0, 100)  # Standardize scale to 100%
ax.legend(title="Publication Status", fontsize=11, title_fontsize=11)

# Annotate values clearly on top of each individual bar for quick reading
for p in ax.patches:
    height = p.get_height()
    if height > 0:  # Skip drawing text for bars with zero height
        ax.annotate(f'{height:.1f}%',
                    xy=(p.get_x() + p.get_width() / 2, height),
                    xytext=(0, 3),  # Offset label slightly above the bar
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig('sample_status_distribution_chart.png')
plt.show()

print("Visualization successfully built and saved as 'sample_status_distribution_chart.png'!")

"""Across all samples, most already animated manga are currently marked as Finished.

Sample C has the highest Publishing share at 27.58%, because it focuses on active-market titles with members >= 1000.

On Hiatus is very small across all samples, around 1.5–1.8%.

However, publication status is based on the current dataset snapshot. It does not necessarily reflect the status at the time when the manga was first licensed or adapted into anime.

## Demographic Distribution

This section shows the most common demographic labels among already animated manga.

Demographic labels describe original publishing target categories. They do not directly represent the actual full audience.

To help clarify these market segments, we break down what each category means:

* **Shounen:** Targeted toward young boys.
* **Seinen:** Targeted toward adult men.
* **Shoujo:** Targeted toward young girls.
* **Josei:** Targeted toward adult women.
* **Kids:** Targeted toward young children.
"""

# ============================================================
# 7. Demographic Distribution
# ============================================================

demo_cols = [col for col in final_df.columns if col.startswith("demo_")]

def demographic_distribution(df, sample_name):
    animated = df[df["has_anime"] == 1].copy()
    total = len(animated)

    rows = []
    for col in demo_cols:
        if col in animated.columns:
            count = int(animated[col].sum())
            rows.append({
                "Sample": sample_name,
                "Demographic": col.replace("demo_", ""),
                "Count": count,
                "Percentage": round(count / total * 100, 2)
            })
    return rows

demo_summary = pd.DataFrame(
    demographic_distribution(sample_a, "Sample A — Score Model")
    + demographic_distribution(sample_b, "Sample B — Favorites Model")
    + demographic_distribution(sample_c_active, "Sample C — Members / Active-Market Model")
)

demo_summary = demo_summary.sort_values(["Sample", "Count"], ascending=[True, False])

display(demo_summary)

demo_summary.to_csv("eda_demographic_distribution.csv", index=False)
demo_summary.to_html("eda_demographic_distribution.html", index=False)

print("Saved files:")
print("eda_demographic_distribution.csv")
print("eda_demographic_distribution.html")

"""## Visualization - Demographic Distribution"""

# Set up visualization style and plot layout
sns.set_theme(style="whitegrid")
fig, ax = plt.subplots(figsize=(12, 6), dpi=100)

# Create a grouped bar chart using seaborn to compare demographic percentages
sns.barplot(
    data=demo_summary,
    x="Sample",
    y="Percentage",
    hue="Demographic",
    palette="Set2",
    alpha=0.9,
    ax=ax
)

# Add clear labels, title, and layout adjustments
ax.set_title('Demographic Profile of Animated Manga Across Samples', fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Data Modeling Samples', fontsize=12, labelpad=10)
ax.set_ylabel('Percentage of Animated Titles (%)', fontsize=12)

# --- CHANGED: Lowered to 30 to perfectly fit our 25.2% maximum data point ---
ax.set_ylim(0, 30)

ax.legend(title="Demographic Group", fontsize=11, title_fontsize=11, loc="upper right")

# Annotate values clearly on top of each individual bar for quick reading
for p in ax.patches:
    height = p.get_height()
    if height > 0:  # Skip drawing text for bars with zero height
        ax.annotate(f'{height:.1f}%',
                    xy=(p.get_x() + p.get_width() / 2, height),
                    xytext=(0, 3),  # Offset label slightly above the bar
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.savefig('sample_demographic_distribution_chart.png')
plt.show()

"""## Genre Distribution

This section shows the most frequent genre tags among already animated manga.

Because one manga can have multiple genres, genre counts are not mutually exclusive.

These counts are descriptive references. They do not prove statistical relationships.
"""

# ============================================================
# 8. Genre Distribution — Already Animated Manga
# ============================================================

genre_cols = [col for col in final_df.columns if col.startswith("genre_")]

def top_genres_animated(df, sample_name, top_n=10):
    animated = df[df["has_anime"] == 1].copy()
    total = len(animated)

    rows = []
    for col in genre_cols:
        if col in animated.columns:
            count = int(animated[col].sum())
            rows.append({
                "Sample": sample_name,
                "Genre": col.replace("genre_", "").replace("_", " ").title(),
                "Count": count,
                "Percentage": round(count / total * 100, 2)
            })

    result = pd.DataFrame(rows)
    result = result.sort_values("Count", ascending=False).head(top_n)
    return result

top_genres_all = pd.concat([
    top_genres_animated(sample_a, "Sample A — Score Model", top_n=10),
    top_genres_animated(sample_b, "Sample B — Favorites Model", top_n=10),
    top_genres_animated(sample_c_active, "Sample C — Members / Active-Market Model", top_n=10)
], ignore_index=True)

display(top_genres_all)

top_genres_all.to_csv("eda_top_genres_animated.csv", index=False)
top_genres_all.to_html("eda_top_genres_animated.html", index=False)

print("Saved files:")
print("eda_top_genres_animated.csv")
print("eda_top_genres_animated.html")

"""## Visualization - Genre Distribution

To map out the most popular themes in the historical animation pipeline, we isolate and rank the top 10 genres for already-animated titles across our three data tracks. Because genres can overlap heavily, this distribution helps us identify key market trends:

* **Core Genre Leaders:** The charts reveal which classic content themes (such as Action, Comedy, or Romance) consistently secure the largest market shares.
* **Sample Shifting:** They show us if changing our filtering rules (like focusing purely on active-market properties in Sample C) alters the ranking order of top genres or surfaces different fan-driven categories.
"""

# Set up the visualization style and a 3-panel layout (one row, three columns)
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1, 3, figsize=(18, 6), sharex=False, dpi=100)

# Extract unique sample names from the summary dataframe
unique_samples = top_genres_all['Sample'].unique()

# Define a cohesive, professional color palette for the plots
subplot_colors = ['cornflowerblue', 'salmon', 'mediumaquamarine']

# Loop through each sample to build its individual horizontal ranking chart
for i, sample in enumerate(unique_samples):
    # Filter the data specifically for the current sample
    sample_data = top_genres_all[top_genres_all['Sample'] == sample].copy()

    # Generate the horizontal bar chart on the corresponding subplot axis
    sns.barplot(
        data=sample_data,
        x="Percentage",
        y="Genre",
        color=subplot_colors[i],
        alpha=0.9,
        ax=axes[i]
    )

    # Add titles, labels, and formatting adjustments for each panel
    clean_title = sample.split(" — ")[0] # Extracts just "Sample A", "Sample B", etc.
    axes[i].set_title(f'{clean_title}: Top 10 Animated Genres', fontsize=12, fontweight='bold', pad=10)
    axes[i].set_xlabel('Percentage of Sample (%)', fontsize=10)
    axes[i].set_ylabel('', style='normal') # Remove vertical axis label to keep it clean

    # Set a clean horizontal limit with some room for text labels
    max_pct = sample_data['Percentage'].max()
    axes[i].set_xlim(0, max_pct + 8)

    # Annotate the exact percentages on the right side of each horizontal bar
    for p in axes[i].patches:
        width = p.get_width()
        if width > 0:
            axes[i].annotate(f'{width:.1f}%',
                             xy=(width, p.get_y() + p.get_height() / 2),
                             xytext=(5, 0),  # Offset label slightly to the right of the bar
                             textcoords="offset points",
                             ha='left', va='center', fontsize=9, fontweight='bold')

# Set a main shared title for the entire visual figure
fig.suptitle('Comparative Profile of Top 10 Animated Genres Across Samples', fontsize=16, fontweight='bold', y=1.02)

plt.tight_layout()
plt.savefig('sample_top_genres_comparison_chart.png', bbox_inches='tight')
plt.show()

print("Visualization successfully built and saved as 'sample_top_genres_comparison_chart.png'!")

"""## Unanimated Candidate Pool: Top Genres

This section shows which genres are most common among unanimated manga titles.

This helps identify genres with large untapped supply, but it does not automatically mean those genres are the best licensing candidates.
"""

# ============================================================
# 9. Genre Distribution — Unanimated Candidate Pool
# ============================================================

def top_genres_unanimated(df, sample_name, top_n=10):
    unanimated = df[df["has_anime"] == 0].copy()
    total = len(unanimated)

    rows = []
    for col in genre_cols:
        if col in unanimated.columns:
            count = int(unanimated[col].sum())
            rows.append({
                "Sample": sample_name,
                "Genre": col.replace("genre_", "").replace("_", " ").title(),
                "Count": count,
                "Percentage": round(count / total * 100, 2)
            })

    result = pd.DataFrame(rows)
    result = result.sort_values("Count", ascending=False).head(top_n)
    return result

candidate_genres = top_genres_unanimated(final_df, "Final Dataset — Candidate Pool", top_n=10)

display(candidate_genres)

candidate_genres.to_csv("eda_top_genres_candidate_pool.csv", index=False)
candidate_genres.to_html("eda_top_genres_candidate_pool.html", index=False)

print("Saved files:")
print("eda_top_genres_candidate_pool.csv")
print("eda_top_genres_candidate_pool.html")

"""## Visualization - Unanimated Pool: Top Genres

To understand what the available market looks like for future animation projects, we isolate and rank the top 10 genres within our **Unanimated Candidate Pool**. Looking at the percentage distribution of these un-adapted titles helps us identify major patterns:

* **Market Supply:** The chart highlights which themes and genres currently have the highest volume of stories waiting for an adaptation.
* **Strategic Opportunities:** By comparing these rankings to our previous charts of already-animated titles, we can see if there are highly populated genres that studios are currently underutilizing.
"""

# Set up the visualization style and a clean single-panel layout
sns.set_theme(style="whitegrid")
fig, ax = plt.subplots(figsize=(10, 6), dpi=100)

# Sort the data to make sure the highest percentage is at the top of the chart
plot_candidates = candidate_genres.sort_values("Percentage", ascending=False)

# Generate a clean horizontal bar chart using a distinct color to represent candidates
sns.barplot(
    data=plot_candidates,
    x="Percentage",
    y="Genre",
    color="darkorange",
    alpha=0.85,
    ax=ax
)

# Add clear titles, labels, and formatting adjustments
ax.set_title('Top 10 Genres in the Unanimated Candidate Pool', fontsize=14, fontweight='bold', pad=15)
ax.set_xlabel('Percentage of Candidate Pool (%)', fontsize=12, labelpad=10)
ax.set_ylabel('', style='normal')  # Remove vertical axis label to keep it clean

# Set a clean horizontal limit with some extra room for the text labels
max_candidate_pct = plot_candidates['Percentage'].max()
ax.set_xlim(0, max_candidate_pct + 5)

# Annotate the exact percentages on the right side of each horizontal bar for quick reading
for p in ax.patches:
    width = p.get_width()
    if width > 0:
        ax.annotate(f'{width:.1f}%',
                    xy=(width, p.get_y() + p.get_height() / 2),
                    xytext=(5, 0),  # Offset label slightly to the right of the bar
                    textcoords="offset points",
                    ha='left', va='center', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.savefig('candidate_pool_top_genres_chart.png', bbox_inches='tight')
plt.show()

print("Visualization successfully built and saved as 'candidate_pool_top_genres_chart.png'!")

"""# Manga Portfolio Selection Benchmarks

This section establishes the data-driven benchmarks (minimum requirements) used to filter out thousands of unadapted manga titles into three distinct target portfolios. These benchmarks are derived directly from our Exploratory Data Analysis (EDA) to ensure we only target high-performing, well-received titles.

---

### The Three Tier Benchmarks

To be considered at all, a manga must first be highly rated with an audience score of $\ge 7.0$. From there, titles are funneled into tiers based on their popularity metrics:

* **Tier 1: Consensus Elite (Mass-Market Blockbusters)**
    * **Minimum Members:** $\ge 5,664$
    * **Minimum Favorites:** $\ge 1,012$
    * These are massive, globally recognized series. They have huge built-in audiences and represent the safest, lowest-risk options for an anime adaptation.
* **Tier 2: Established Contenders (Steady Mainstream Hits)**
    * **Minimum Members:** $\ge 3,912$
    * **Minimum Favorites:** $\ge 856$
    * These are solid, reliable mainstream titles that sit just below the top blockbusters. They offer great performance and high popularity but come with lower licensing costs.
* **Tier 3: High-Passion Hidden Gems (Cult Classics)**
    * **Minimum Members:** $\ge 1,316$
    * **Minimum Favorites:** $\ge 557$
    * These titles have smaller overall member counts but highly passionate, fanatical fanbases (proven by their high favorite counts relative to their small size). They represent high-return, niche opportunities.

---

### Why We Use These Benchmarks

* **Cuts Out the Noise:** Out of over $77,000$ unanimated titles in the database, the vast majority are completely obscure or abandoned projects. These rules instantly clear out the bottom $99.6\%$ of market noise.
* **Guarantees Quality:** Setting a strict minimum score of $7.0$ ensures we only look at projects that are proven to satisfy readers.
* **Fits Different Budgets:** Instead of a single list, it gives a media company three distinct investment pathways depending on whether they want a huge expensive flagship (Tier 1), a stable mid-market hit (Tier 2), or a cheap but high-passion cult classic (Tier 3).

## Diagnostic Notes and Limitations

Several limitations exist.

1. The dataset is based on MyAnimeList, which may reflect global and Western fan behavior more strongly than the entire Japanese domestic market. This is a limitation, but it also fits our project perspective because our point of view is a US-based animation studio, thus, favouring global viewership rather than just the Japanese market.

2. Score has many missing values, which is why we created a separate score-based sample.

3. Members and favorites are highly skewed. A small number of mega-hit titles have extremely high engagement, while many titles have much lower values.

4. Title matching may contain errors because of alternative titles, spin-offs, translations, and different naming conventions.

5. Publication status reflects the current dataset snapshot. It does not necessarily reflect the historical status at the time of licensing or first anime adaptation.
"""